`timescale 1ns / 1ps

module gelu_pwl_lut (
    input  logic        clk,
    input  logic        rst_n,
    
    // Input Interface (Q8.8 Signed Fixed-Point)
    input  logic signed [15:0] data_in,
    input  logic               valid_in,
    
    // Output Interface (Q8.8 Signed Fixed-Point)
    output logic signed [15:0] data_out,
    output logic               valid_out
);

    // --- Constants & Parameters ---
    localparam int FRAC_BITS = 8;
    
    // Bounds: -4.0 and +4.0 in Q8.8 format (4 * 256 = 1024)
    localparam signed [15:0] LOWER_BOUND = -16'sd1024;
    localparam signed [15:0] UPPER_BOUND =  16'sd1024;
    
    // Unity Slope (1.0) in Q8.8 format
    localparam signed [15:0] SLOPE_ONE = 16'sd256;

    // --- Memory Initialization (ROM) ---
    // 16 entries, 32-bits wide (16-bit Slope + 16-bit Bias)
    (* rom_style = "distributed" *) // Hint for synthesis tool to use LUTRAM
    logic [31:0] rom_memory [0:15];

    initial begin
        // Load the hex file generated by Python
        $readmemh("gelu_lut.mem", rom_memory);
    end

    // --- Pipeline Signals ---
    
    // Stage 1: Address Gen & ROM Fetch
    logic signed [15:0] x_p1;
    logic signed [15:0] slope_p1;
    logic signed [15:0] bias_p1;
    logic               valid_p1;
    logic [3:0]         lut_index;

    // Stage 2: Arithmetic (MAC)
    logic signed [31:0] mult_result;  // Q16.16
    logic signed [31:0] bias_shifted; // Q16.16
    logic               valid_p2;

    // Stage 3: Final Adder & Rounding
    logic signed [31:0] final_sum;
    
    // --- Stage 1: Address Decoding ---
    // Calculate index: Map [-1024, 1024] range to [0, 15] index
    // (data_in + 1024) >> 7 performs this mapping for step size 0.5 (128 in Q8.8)
    assign lut_index = (data_in + 16'd1024) >>> 7;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            x_p1     <= '0;
            slope_p1 <= '0;
            bias_p1  <= '0;
            valid_p1 <= '0;
        end else begin
            valid_p1 <= valid_in;
            x_p1     <= data_in;

            // Boundary Checks
            if (data_in <= LOWER_BOUND) begin
                // x < -4.0 -> Output is 0
                slope_p1 <= '0;
                bias_p1  <= '0;
            end 
            else if (data_in >= UPPER_BOUND) begin
                // x > 4.0 -> Output is x (Identity: Slope=1, Bias=0)
                slope_p1 <= SLOPE_ONE;
                bias_p1  <= '0;
            end 
            else begin
                // -4.0 < x < 4.0 -> Use Piecewise Linear Approximation
                // Fetch Slope (Upper 16 bits) and Bias (Lower 16 bits)
                {slope_p1, bias_p1} <= rom_memory[lut_index];
            end
        end
    end

    // --- Stage 2: Multiplication ---
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            mult_result  <= '0;
            bias_shifted <= '0;
            valid_p2     <= '0;
        end else begin
            valid_p2 <= valid_p1;
            
            // Multiply Input * Slope (Result becomes Q16.16)
            mult_result <= x_p1 * slope_p1;
            
            // Shift Bias to align with Multiplication result (Q8.8 -> Q16.16)
            bias_shifted <= {{8{bias_p1[15]}}, bias_p1, 8'b0}; 
        end
    end

    // --- Stage 3: Addition & Truncation ---
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            data_out  <= '0;
            valid_out <= '0;
        end else begin
            valid_out <= valid_p2;

            // Calculate y = mx + c
            final_sum = mult_result + bias_shifted;

            // Normalize back to Q8.8
            // Discard lower 8 bits, keep middle 16 bits
            // Optional: Add rounding logic here if needed
            data_out <= final_sum[23:8]; 
        end
    end

endmodule